### ISSUE TITLE
code typo in example

### ISSUE THREAD

**Issue by danielwpz** [near/workspaces-js#100]
hey, I found the example writes:
```
  const attachedDeposit = '2 N';

  // This adds the key as a function access key on `create_account_and_claim`
  await root.call(linkdrop, 'send', {public_key}, {attachedDeposit});
```
however the attachedDeposit cannot be a string, it has to be a NEAR parsed object.

https://github.com/near/workspaces-js/blob/main/__tests__/03.single-use-access-keys-with-linkdrop.ava.ts#L42

Is this a typo? If so I can help fix the example

**Comment by volovyk-s** [comment]
It's passed as an object. When we are passing parameters with brackets they are passed as an object.
```JavaScript
const someString = 'yo';
someFunc(someString);  <- passed as a string
someFunc({ someString });  <- passed as an object, transformed to "{"someString": "yo"}"
```
Other parameters in this type are optional, so it's ok.
But you can make a PR that will have more self explanatory code, thanks :)

**Comment by willemneal** [comment]
@danielwpz It hasn't been published yet, but you can assign a string to `attachedDeposit`, see https://github.com/near/workspaces-js/pull/99
