### ISSUE TITLE
Clarification on the using other testing libraries comment

### ISSUE THREAD

**Issue by jackrobsonalpha** [near/workspaces-js#104]
Hi team,

In the docs you say;
`If you prefer a testing library other than AVA, you can use near-workspaces-js directly.`

I'd love a slight expansion on the steps one would do for this.

I have managed to get the `Workspace.init` command to work, see my gist here:
https://gist.github.com/jackrobsonalpha/7a33d41951c8d8915b27f335f4270f80

And I've got it to wait for the workspace to load before it continues.

However it still fails at `workspace.test(` giving the error:
```    workspace.test('root sets status', async (test, {contract, root}) => {
    TypeError: workspace.test is not a function```
    
I know the  near-workspace-js Workspace class does not have a test function.

And I can't work out how Ava is doing this. 

Could you explain how to get my next workspace.test (or another function that uses the workspace) to work?

Code is good but even just an explanation would really help.

Regards,
Jack

**Comment by Amacc** [comment]
As for the how is Ava doing this it looks like the test function is here:

https://github.com/near/workspaces-js/blob/c6a6261873aee76930deff3053f9582595b528fb/packages/ava/src/index.ts#L110

But to implement your own just require your testing tool of choice and pass the required arguments in place of the workstation.test calls. Hope that helps.

**Comment by jackrobsonalpha** [comment]
Ah, I did not realise ava was a testing framework.

I thought it was a Nears solution to get mocha tests of sorts.

Thank you for the clarification.

Using your insights I can see what I need todo.

Might be able to use the Workspace fork function.
