### ISSUE TITLE
Should still provide help for setting up ava

### ISSUE THREAD

**Issue by willemneal** [near/workspaces-js#132]
The last PR deleted near-workspaces-ava, but we should still provide the config files for users to help them set up a new project.

We should make it as frictionless as we can for new projects to use ava.  As I haven't seen any resolution of the concurrency issues we had when using jest.

**Comment by volovyk-s** [comment]
@willemneal what do you mean by config files? We still have testnet config example.

**Comment by willemneal** [comment]
> https://github.com/near/workspaces-js/blob/4d3767b1adc6417d9b92e863e85edb0ca0e96b4e/packages/ava/ava.config.cjs

> https://github.com/near/workspaces-js/blob/4d3767b1adc6417d9b92e863e85edb0ca0e96b4e/packages/ava/ava.testnet.config.cjs

> https://github.com/near/workspaces-js/blob/4d3767b1adc6417d9b92e863e85edb0ca0e96b4e/packages/ava/tsconfig.ava.json

These let projects depend on these files without having to write them themselves.  In general, I'd recommend trying to start a new project from scratch and finding the parts that are hard.

Also any luck with jest?  `test.concurrent` was having issues last time we tried.

**Comment by willemneal** [comment]
Ah great just making sure! Thanks!

**Comment by ailisp** [comment]
We recently added an example setup examples/simple-project in repo and setup in existing project example: https://github.com/near-examples/rust-counter/tree/master/integration-tests/ts
